### ISSUE TITLE
[Enhancement] ms room selection

### ISSUE THREAD

**Issue by aquifolly** [Bijman/srb2srv#1]

**Comment by Bijman** [comment]
Does this proposed enhancement is for filtering Master Server list to selected room to connect to someone's server? Please elaborate.

**Comment by aquifolly** [comment]
yes

**Comment by aquifolly** [comment]
sometimes I can see servers in the in-game server browser that I can't see in srb2srv

**Comment by aquifolly** [comment]
or in the online viewer for that matter

**Comment by Bijman** [comment]
Added this feature with commit fb46002. To run it, enter `srb2srv --room [NAME OF SRB2 MASTER SERVER ROOM: standard/casual/custom] `
